# GitLab CI/CD Pipeline for NixOS Kubernetes Infrastructure  
# 
# STATUS: Phase 2 - Basic validation only
# Primary workflow is local CLI usage (see README.md)
# Full deployment pipeline planned for Phase 3+

variables:
  TERRAFORM_VERSION: "1.13.0-beta1"
  TF_ROOT: "${CI_PROJECT_DIR}/terraform"

# Global settings
default:
  image: hashicorp/terraform:${TERRAFORM_VERSION}
  tags:
    - homelab
  before_script:
    - cd ${TF_ROOT}
    - terraform --version

stages:
  - validate

# Validate Terraform configuration (Phase 2 scope)
tf:validate:
  stage: validate
  script:
    - terraform init -backend=false  # Skip backend for validation
    - terraform fmt -check -recursive  
    - terraform validate
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  allow_failure: true

# TODO: Phase 3+ - Add multi-environment deployment pipeline
# - Environment-specific variables (DEV_*, PROD_*)  
# - Branch-based deployment (dev branch → dev env, main → prod)
# - S3 backend integration
# - Manual approval gates
# - Proper plan/apply workflow