---
# Ansible Inventory Template
# Generated by Terraform - Customize as needed

all:
  children:
    project_vms:
      hosts:
%{ for vm in vms ~}
        ${vm.vm_name}:
          ansible_host: ${vm.ip_address}
          ansible_user: ${ssh_user}
          ansible_ssh_private_key_file: ${ssh_private_key}
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          vm_id: ${vm.vm_id}
%{ endfor ~}
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    # Example groupings for different VM roles
    # web_servers:
    #   hosts:
    #     vm-name-1:
    #   vars:
    #     server_role: web
    
    # db_servers:
    #   hosts:
    #     vm-name-2:
    #   vars:
    #     server_role: database