---
# Ansible Inventory for Ubuntu Servers
# Generated by Terraform

all:
  children:
    ubuntu_servers:
      hosts:
%{ for server in servers ~}
        ${server.vm_name}:
          ansible_host: ${server.ip_address}
          ansible_user: ${ssh_user}
          ansible_ssh_private_key_file: ${ssh_private_key}
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          vm_id: ${server.vm_id}
%{ endfor ~}
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    # Example groupings for different server roles
    # web_servers:
    #   hosts:
    #     ubuntu-dev-1-xxxxxx:
    #   vars:
    #     server_role: web
    
    # db_servers:
    #   hosts:
    #     ubuntu-dev-2-xxxxxx:
    #   vars:
    #     server_role: database